migrate to cats-effect
NewMotion/ocpi-endpoints pull request #77
Opened 2021-02-02 11:50 UTC by poohsen

Migrate effect type to cats-effect IO.
At the core, we still use akka-http for routes and clients so we need the typical akka implicits. 
Stream sources are also still using akka-stream.
But at the interface to the backend services implemented by the calling application code, IO (or ZIO) can be
used to model effect types.

In the following phases, we should migrate further to http4s, sttp (?) and fs2.

2021-02-17 10:14 UTC, pierangeloc requested changes
Suggested a couple of improvements, for the rest this is a great change!
Next step I would do: model all the routes in terms of Tapir endpoints so we can get akka-http, http4s, sttp clients and routes for free

2021-02-22 13:19 UTC, pierangeloc commented on endpoints-common/src/test/scala/com/thenewmotion/ocpi/common/HktMarshallableFromECInstances.scala
> +  implicit def ioCsFromEcMarshaller(implicit ec: ExecutionContext): HktMarshallable[IO] = new HktMarshallable[IO] {
`ContextShift` is a typeclass, so you can have it working for a particular F

```scala
object HktMarshallableFromECInstances {

  implicit def ioCsFromEcMarshaller[F[_]: ContextShift](implicit ec: ExecutionContext): HktMarshallable[F] = new HktMarshallable[F] {
    def responseMarshaller[A](implicit m: ToResponseMarshaller[A]): ToResponseMarshaller[F[A]] = {
      GenericMarshallers.futureMarshaller(m).compose(io => (ContextShift[F].shift *> io).unsafeToFuture())
    }

    def requestMarshaller[A](implicit m: ToRequestMarshaller[A]): ToRequestMarshaller[F[A]] = {
      GenericMarshallers.futureMarshaller(m).compose(io => (ContextShift[F].shift *> io).unsafeToFuture())
    }
  }

  implicit def idMarshaller: HktMarshallable[Id] = new HktMarshallable[Id] {
    def responseMarshaller[A: ToResponseMarshaller]: ToResponseMarshaller[A] = implicitly
    def requestMarshaller[A : ToRequestMarshaller]: ToRequestMarshaller[A] = implicitly
  }
}
```

2021-02-22 13:28 UTC, pierangeloc commented on endpoints-common/src/test/scala/com/thenewmotion/ocpi/common/HktMarshallableFromECInstances.scala
> +  implicit def ioCsFromEcMarshaller(implicit ec: ExecutionContext): HktMarshallable[IO] = new HktMarshallable[IO] {
```scala
package com.thenewmotion.ocpi.common

import akka.http.scaladsl.marshalling.{GenericMarshallers, ToRequestMarshaller, ToResponseMarshaller}
import cats.Id
import cats.effect.{Effect, ContextShift}
import cats.syntax.all._

import scala.concurrent.ExecutionContext

/**
  * Convenience marshallers to help keep test code clean
  */
object HktMarshallableFromECInstances {

  implicit def ioCsFromEcMarshaller[F[_]](implicit ec: ExecutionContext, effect: Effect[F], cs: ContextShift[F]): HktMarshallable[F] = new HktMarshallable[F] {
    def responseMarshaller[A](implicit m: ToResponseMarshaller[A]): ToResponseMarshaller[F[A]] = {
      GenericMarshallers.futureMarshaller(m).compose(io => effect.toIO(cs.shift *> io).unsafeToFuture())
    }

    def requestMarshaller[A](implicit m: ToRequestMarshaller[A]): ToRequestMarshaller[F[A]] = {
      GenericMarshallers.futureMarshaller(m).compose(io => effect.toIO(cs.shift *> io).unsafeToFuture())
    }
  }

  implicit def idMarshaller: HktMarshallable[Id] = new HktMarshallable[Id] {
    def responseMarshaller[A: ToResponseMarshaller]: ToResponseMarshaller[A] = implicitly
    def requestMarshaller[A : ToRequestMarshaller]: ToRequestMarshaller[A] = implicitly
  }
}
```

2021-02-22 13:36 UTC, poohsen commented on endpoints-common/src/test/scala/com/thenewmotion/ocpi/common/HktMarshallableFromECInstances.scala
> +  implicit def ioCsFromEcMarshaller(implicit ec: ExecutionContext): HktMarshallable[IO] = new HktMarshallable[IO] {
but then you need  `ContextShift[F]` in implicit scope. These instances are used in the tests where we get the executioncontext passed into the test class by specs2, that's why i wanted something that works with just the ExecutionContext in implicit scope.  I figured that it's OK to hardcode to IO in the tests.
If there's a way to make that generic then I'll do it ofc.

2021-02-24 16:15 UTC, merged